In [8]:
import pandas as pd
import random
from faker import Faker
fake = Faker()

In [13]:
#generation of random people and their pronouns
pronoun_preferences = [
    "she/her",
    "he/him",
    "they/them",
    "xe/xer"
]

number_of_people = 100

people = pd.DataFrame({
    "ID":range(1, number_of_people + 1),
    "Name": [fake.name() for _ in range(number_of_people)],
    "Pronouns": [random.choice(pronoun_preferences) for _ in range(number_of_people)]
})
people.head()

   ID               Name   Pronouns
0   1        Joanne Carr     xe/xer
1   2  Patricia Thompson  they/them
2   3     Harold Johnson  they/them
3   4         Jill Kirby     xe/xer
4   5    Kristen Anthony     he/him

In [14]:
#generations of connections with at least 1-3 people
connective_lst = []
for person_id in people["ID"]:
    number_of_connections = random.randint(1,3)
    potential_connection = [pid for pid in people["ID"] if pid != person_id]
    connect_ids = random.sample(potential_connection, number_of_connections)
    for conid in connect_ids:
        connective_lst.append({
            "FromID": person_id,
            "ToID": conid
        })
connections = pd.DataFrame(connective_lst)
connections.head()

   FromID  ToID
0       1    44
1       1    35
2       1    94
3       2    83
4       2    21

In [15]:
#merging both people and pronouns into a singular excel sheet
merging = connections.merge(
    people, left_on="FromID", right_on="ID"
).merge(
    people, left_on="ToID", right_on="ID", suffixes=("_From", "_To")
)

final = merging[[
    "Name_From", "Pronouns_From",
    "Name_To", "Pronouns_To"
]]

final.head()

           Name_From Pronouns_From            Name_To Pronouns_To
0        Joanne Carr        xe/xer       Rachel Klein   they/them
1        Joanne Carr        xe/xer       Ronald Myers     she/her
2        Joanne Carr        xe/xer  Patricia Ferguson     she/her
3  Patricia Thompson     they/them     Cory Rodriguez   they/them
4  Patricia Thompson     they/them      Russell Dixon   they/them

In [16]:
#excel export
final.to_csv("people_connections_to_pronouns_100.csv", index=False, encoding='utf-8-sig')